// <auto-generated />
namespace ProjectCoffee.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Changeduserfields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changeduserfields));
        
        string IMigrationMetadata.Id
        {
            get { return "201612192123272_Changed user fields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
